# Site settings
title: ZStack
email: info@zstack.org

name: "zstack"
description: "ZStack is open source IaaS software managing resources of compute, storage, networking throughout a datacenter all by APIs."

#contacts
twitter_username: "zstack_org"

baseurl: ""
url: "http://zstack.org"


# Build settings
markdown: rdiscount
permalink: none
highlighter: pygments
relative_permalinks: false

# multiple languages plugins.
gems:           ['jekyll-multiple-languages']

languages:          ['en', 'cn']
#
language_default:   'en'
#
fill_default_content: true

vr_en: "http://cdn.zstack.io/product_downloads/vrouter/zstack-vrouter-2.0.0.qcow2"
all_in_one_en: "http://cdn.zstack.io/community/downloads/zstack/2.0/ZStack-installer-2.0.1.bin"
war_en: "http://cdn.zstack.io/product_downloads/war/zstack-2.0.1.war"
tgz: "ZStack-installer-2.0.1.bin"


vr_ch: "http://cdn.zstack.io/product_downloads/vrouter/zstack-vrouter-2.0.0.qcow2"
all_in_one_ch: "http://cdn.zstack.io/community/downloads/zstack/2.0/ZStack-installer-2.0.1.bin"
#all_in_one_ch: "http://7xi3lj.com1.z0.glb.clouddn.com/releases/1.0/1.0.1/zstack-installer-1.0.1.bin"
#war_ch: "http://7xi3lj.com1.z0.glb.clouddn.com/releases/1.0/1.0.1/zstack.war"
war_ch: "http://cdn.zstack.io/product_downloads/war/zstack-2.0.1.war"
all_in_one_md5: "47945cc8644006a8537db408896df0e7"

zstack_image: "http://cdn.zstack.io/product_downloads/images/zstack-image.qcow2"
zstack_image_md5: "495c94a97c25c1290befb083f40181f0"

zstack_centos7_name: "ZStack-x86_64-DVD-2.0.1.iso"
zstack_centos7_iso: "http://cdn.zstack.io/community/downloads/iso/ZStack-x86_64-DVD-2.0.1.iso"
zstack_centos7_md5: "07186ae6023b3e7e9b820324c5c00cbf"

